source tcl_scripts/B/create_B_11_11.tcl
source tcl_scripts/B/create_B_11_12.tcl
source tcl_scripts/B/create_B_11_21.tcl
source tcl_scripts/B/create_B_11_22.tcl
source tcl_scripts/B/create_B_12_11.tcl
source tcl_scripts/B/create_B_12_12.tcl
source tcl_scripts/B/create_B_12_21.tcl
source tcl_scripts/B/create_B_12_22.tcl
source tcl_scripts/B/create_B_21_11.tcl
source tcl_scripts/B/create_B_21_12.tcl
source tcl_scripts/B/create_B_21_21.tcl
source tcl_scripts/B/create_B_21_22.tcl
source tcl_scripts/B/create_B_22_11.tcl
source tcl_scripts/B/create_B_22_12.tcl
source tcl_scripts/B/create_B_22_21.tcl
source tcl_scripts/B/create_B_22_22.tcl
